# docker-compose.yml - для локального тестирования
version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom_postgres
    environment:
      # Эти переменные можно переопределить в .env файле или при запуске
      POSTGRES_USER: ${DATABASE_USER:-myuser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-mypassword}
      POSTGRES_DB: ${DATABASE_NAME:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      # Персистентное хранение данных
      - postgres_data:/var/lib/postgresql/data
      # Дополнительные логи (опционально)
      - ./logs:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-myuser} -d ${DATABASE_NAME:-mydatabase}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
